version: 2

sources:
  - name: snowflake_sample_data
    description: 'Snowflake Sample Data Set.'
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1000
    tables:
      - name: orders
        description: 'Part orders'